### ISSUE TITLE
Concern about the last two experiments with Sentiment140 and Reddit datasets

### ISSUE THREAD

**Issue by judydnguyen** [ksreenivasan/OOD_Federated_Learning#5]
First of all, I want to thank you all cause you share this repo to all of us. I've read your paper and try to improve something using your code. However, I find out that it seems like you haven't implement the last 2 experiments with Sentiment140 and Reddit datasets, have you?

**Comment by ksreenivasan** [comment]
Hi @thuydung-icthust thank you for your interest in our project! I'm so sorry about that. The language tasks were implemented separately and weren't included in our codebase. If you reach out to me at ksreenivasa2@wisc.edu, I can put you in touch with my co-author and we can see if we can find it :)

**Comment by harit7** [comment]
@thuydung-icthust 

For the sentiment140 task you can find the code and data here
https://github.com/ksreenivasan/OOD_Federated_Learning/tree/master/language-tasks-fl

The same task is maintained in the following repository with few more additional details,
https://github.com/harit7/torch-fl 
 
For the reddit task we used the same setup as in https://github.com/ebagdasa/backdoor_federated_learning

**Comment by judydnguyen** [comment]
> @thuydung-icthust
> 
> For the sentiment140 task you can find the code and data here https://github.com/ksreenivasan/OOD_Federated_Learning/tree/master/language-tasks-fl
> 
> The same task is maintained in the following repository with few more additional details, https://github.com/harit7/torch-fl
> 
> For the reddit task we used the same setup as in https://github.com/ebagdasa/backdoor_federated_learning

Thank your very much <3 I really appreciate your kindness. Wish you all the best and greater work in the future.

**Comment by judydnguyen** [comment]
> Hi @thuydung-icthust thank you for your interest in our project! I'm so sorry about that. The language tasks were implemented separately and weren't included in our codebase. If you reach out to me at [ksreenivasa2@wisc.edu](mailto:ksreenivasa2@wisc.edu), I can put you in touch with my co-author and we can see if we can find it :)

Yeah, I've got the code I'm looking for right below your comment! Thanks a lot and I love reading your papers actually <3
