### ISSUE TITLE
Total number of client.

### ISSUE THREAD

**Issue by nhduong1203** [ksreenivasan/OOD_Federated_Learning#8]
Hi, I have run the experiment, once I change the total number of clients, but stay the same number of clients participate per round, the defense's accuracy of detecting attacker drop. I think the different is the datasize per client now have been change, but why it cause the attacker more effective?

**Comment by ksreenivasan** [comment]
Hi @nhduong1203, like you mentioned, you are changing the fraction of total data points available to the attacker. Though we didn't explicitly test this, it looks like the behavior should be similar to Fig 4 in our paper. Hope this helps!

**Comment by nhduong1203** [comment]
Thanks you, I think when I decrease the total number of clients, the dataset for each benign client will become bigger, so it's now bigger than the attacker's dataset. Then the benign's model will dominate the weights of the attacker's model when average. So it's harder for defender to detect attacker, but now the effectiveness of the attack is very low (Backdoor Accuracy low).
